### ISSUE TITLE
Colors in the last update

### ISSUE THREAD

**Issue by rubenmoya** [smlombardi/oceanic-next-syntax#10]
So, everything is blueish-green in the last update, method definitions, class definitions..

Example (class used to be purple):

![screen shot 2016-08-22 at 15 02 24](https://cloud.githubusercontent.com/assets/905225/17855536/83e30b6e-6879-11e6-8a90-fbaae622f4c0.png)

**Comment by kaylaharris24** [comment]
@rubenmoya You can go and change the code yourself to get the purple color back, at least that's what I did. 

I just removed `.keyword.control` from line 72 and put it on line 68. If your line numbers are different then you can reference it by just adding `.keyword.control` to the line that has the declaration specifying `color: #C594C5;`

**Comment by rubenmoya** [comment]
@kaylacohn Thanks for answering! Yep, that's what I did, the green color was driving me crazy haha

**Comment by smlombardi** [comment]
@kaylacohn @rubenmoya Please feel free to make a pull request with this fix.  That's how it changed in the first place, someone else changed it to green. Since purple is better, why not share it with everyone? Thanks.

**Comment by kaylaharris24** [comment]
@smlombardi will do!

**Comment by MethodGrab** [comment]
PR added.

**Comment by smlombardi** [comment]
Reverted as per PR https://github.com/smlombardi/oceanic-next-syntax/commit/c8006db2ba9a885bddd919ac0807c25b7c7cede2
