### ISSUE TITLE
inclusion in atom package manager?

### ISSUE THREAD

**Issue by oldo** [smlombardi/oceanic-next-syntax#19]
Any reason why this isn't included in `apm`?

**Comment by smlombardi** [comment]
I thought it was.

**Comment by oldo** [comment]
![screen shot 2017-04-16 at 14 06 13](https://cloud.githubusercontent.com/assets/4557648/25068644/e4218692-22ad-11e7-94a7-58f1e2298f0d.png)

**Comment by smlombardi** [comment]
Beats me.  I published it ages ago.  Maybe they deleted it?  Anyway, I don't use Atom any longer so I won't be supporting these themes.
