### ISSUE TITLE
Add complete support to ES6

### ISSUE THREAD

**Issue by gsklee** [smlombardi/oceanic-next-syntax#3]
I thought this package supports all new syntax in ES6 but apparently it's not:

![http://i.imgur.com/mlAEfJm.png](http://i.imgur.com/mlAEfJm.png)

In this example `export` should be highlighted as well.

**Comment by smlombardi** [comment]
The actual selectors for the ES6 need to be done in the language, not the theme.  Someone in the language file creates a regex to detect a pattern for something in the language, names it as a scope, and then themers can hook into the scope to change colors etc.  I you detect any _scopes_ that exsit but aren't colored or colored wrong, please let me know.
