### ISSUE TITLE
Misaligned cursor due to new indent-guide placement

### ISSUE THREAD

**Issue by klapec** [smlombardi/oceanic-next-syntax#5]
Since 415f9d9931590683b473a076374e4fc276b1be9b, the mouse cursor is displayed incorrectly in the editor. Due to the change how the indentation guide is placed (from being an inset `box-shadow` to a `border-left`), the cursor is displayed slightly to the left from the desired position.

Currently:
![Currently](http://i.imgur.com/1EdQ69z.png)

Expected:
![Expected](http://i.imgur.com/tF9JDNe.png)

Should we fall back to `box-shadow` and lose the dotted style from the original ST3 theme or is there any other way to fix this?

**Comment by smlombardi** [comment]
I reverted that selector back to the original commit, which was

```
atom-text-editor .indent-guide, :host .indent-guide {
  color: @syntax-indent-guide-color;
}
```

Seems to have fixed it form me.

**Comment by klapec** [comment]
Yup, I've done the same here locally. This issue can be closed.
