### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by floriangosse** [smlombardi/oceanic-next-syntax#9]

**Comment by floriangosse** [comment]
What means the closing of the issue? Is a new version published?

**Comment by smlombardi** [comment]
What's the issue?
there's no description/explanation?

**Comment by floriangosse** [comment]
Sorry, for this unclear title. What I mean is a new version on apm which contains the changes since the last version on apm.

**Comment by smlombardi** [comment]
Done.  Thanks.
